# Generated by Django 5.1.2 on 2024-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_remove_lesson_id_lesson_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
