# Generated by Django 5.1.2 on 2024-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
