# Generated by Django 5.1.2 on 2024-10-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='id',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
