# Generated by Django 5.1.2 on 2024-11-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_quiz_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='option_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
